---
- name: Deploy TRY100 Chatbot to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    k8s_dir: "{{ playbook_dir }}/../k8s"

  tasks:
    - name: Verify kubectl is available
      command: kubectl version --client
      register: kubectl_check
      failed_when: kubectl_check.rc != 0

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f "{{ k8s_dir }}/deployment.yaml"
      register: deploy_out
      failed_when: deploy_out.rc != 0

    - name: Apply Kubernetes Service
      command: kubectl apply -f "{{ k8s_dir }}/service.yaml"
      register: svc_out
      failed_when: svc_out.rc != 0

    - name: Wait for pods to be ready
      command: kubectl rollout status deployment/try100-deployment
      register: rollout_status
      retries: 5
      delay: 10
      until: rollout_status.rc == 0

    - name: Display deployment status
      debug:
        msg: |
          ✅ Deployment and Service applied successfully!
          {{ deploy_out.stdout }}
          {{ svc_out.stdout }}
