name: CI/CD Pipeline — Docker Hub + Kubernetes + Ansible (Self-Hosted Windows)

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    name: Build, Test, and Push Docker Image
    runs-on: self-hosted      # your local runner
    defaults:
      run:
        shell: powershell        # use PowerShell on Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔸 use the Python already installed on your machine
      - name: Verify Python
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: python -m pytest -q

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/try100:latest

  deploy:
    name: Deploy to Kubernetes using Ansible
    needs: build-test-push
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔸 you already have kubectl + ansible configured locally
      - name: Verify tools
        run: |
          kubectl version --client
          ansible --version
          kubectl get nodes

      - name: Run Ansible Playbook for Deployment
        run: ansible-playbook ansible/deploy_k8s.yml
