name: CI/CD Pipeline — Docker Hub + Kubernetes + Ansible (Windows + WSL Ubuntu)

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    name: Build, Test, and Push Docker Image
    runs-on: self-hosted-windows   # 👈 Windows runner label
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Python
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: python -m pytest -q

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/try100:latest

  deploy:
    name: Deploy to Kubernetes using Ansible (inside Ubuntu)
    needs: build-test-push
    runs-on: self-hosted-ubuntu    # 👈 Ubuntu runner label
    defaults:
      run:
        shell: bash                # 👈 Run Ansible commands natively in Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify tools
        run: |
          kubectl version --client
          ansible --version
          kubectl get nodes

      - name: Run Ansible Playbook
        run: ansible-playbook /mnt/c/Users/John\ Israel/Desktop/try100/ansible/deploy_k8s.yml
